# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pupil_markup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 680)
        self.pushButtonOpenImage = QtWidgets.QPushButton(Dialog)
        self.pushButtonOpenImage.setGeometry(QtCore.QRect(20, 10, 100, 25))
        self.pushButtonOpenImage.setObjectName("pushButtonOpenImage")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 540, 540))
        self.groupBox.setObjectName("groupBox")
        self.labelImage = QtWidgets.QLabel(self.groupBox)
        self.labelImage.setGeometry(QtCore.QRect(10, 30, 500, 500))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.listViewSelectedPoints = QtWidgets.QListView(Dialog)
        self.listViewSelectedPoints.setGeometry(QtCore.QRect(570, 120, 200, 200))
        self.listViewSelectedPoints.setObjectName("listViewSelectedPoints")
        self.labelEllipseEquation = QtWidgets.QLabel(Dialog)
        self.labelEllipseEquation.setGeometry(QtCore.QRect(150, 70, 450, 20))
        self.labelEllipseEquation.setObjectName("labelEllipseEquation")
        self.labelEllipseEquationText = QtWidgets.QLabel(Dialog)
        self.labelEllipseEquationText.setGeometry(QtCore.QRect(20, 70, 110, 20))
        self.labelEllipseEquationText.setObjectName("labelEllipseEquationText")
        self.labelSourceImagePath = QtWidgets.QLabel(Dialog)
        self.labelSourceImagePath.setGeometry(QtCore.QRect(130, 15, 400, 17))
        self.labelSourceImagePath.setObjectName("labelSourceImagePath")
        self.pushButtonSetOutput = QtWidgets.QPushButton(Dialog)
        self.pushButtonSetOutput.setGeometry(QtCore.QRect(20, 40, 100, 25))
        self.pushButtonSetOutput.setObjectName("pushButtonSetOutput")
        self.labelOutputMarkupPath = QtWidgets.QLabel(Dialog)
        self.labelOutputMarkupPath.setGeometry(QtCore.QRect(130, 45, 400, 17))
        self.labelOutputMarkupPath.setObjectName("labelOutputMarkupPath")
        self.pushButtonSaveMarkup = QtWidgets.QPushButton(Dialog)
        self.pushButtonSaveMarkup.setGeometry(QtCore.QRect(570, 330, 201, 51))
        self.pushButtonSaveMarkup.setObjectName("pushButtonSaveMarkup")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonOpenImage.setText(_translate("Dialog", "Open image"))
        self.groupBox.setTitle(_translate("Dialog", "Image"))
        self.labelEllipseEquation.setText(_translate("Dialog", "Ax2 + Bxy + Cy2 + Dx + Ey + F = 0"))
        self.labelEllipseEquationText.setText(_translate("Dialog", "Ellipse quation:"))
        self.labelSourceImagePath.setText(_translate("Dialog", "Source image path"))
        self.pushButtonSetOutput.setText(_translate("Dialog", "Set markup"))
        self.labelOutputMarkupPath.setText(_translate("Dialog", "Output markup path"))
        self.pushButtonSaveMarkup.setText(_translate("Dialog", "Save"))
