dataset:
  train:
    tfrecords:
      - /home/igor/datasets/eye_tracker/tfrecords/pupil_train.tfrecord
    batch_size: 32
  val:
    tfrecords:
      - /home/igor/datasets/eye_tracker/tfrecords/pupil_val.tfrecord
    batch_size: 8
model:
  input_size: 64
  pretrained:
    enable: 0
    path: path_to_model.ckpt
  feature_extractor: MobileNetV2
  dropout: 0.5
training:
  epochs: 500
  logs_path: logs
  checkpoints_path: checkpoints
  optimizer: Adam
  lr: 1e-4
  loss_weights:
    regression: 1.
    classification: 5.
